### ISSUE TITLE
Smash Karts

### ISSUE THREAD

**Issue by ISskYT** [Radon-Games/Radon-Games#104]
### Game Name

Smash Karts

### Game Description

Smash Karts is a 3D multiplayer kart battle game. Drive your go-kart, pick up weapons, and blow up other karts to win! Keep playing to level up and unlock new characters and prizes.

### Game URL

https://smashkarts.io/

### Game Type

Online

### Game Tags/Genres

Action

**Comment by cohenerickson** [comment]
Use proxy.
