### ISSUE TITLE
[Game Request]: Vex 6

### ISSUE THREAD

**Issue by zkayns** [Radon-Games/Radon-Games#108]
### Game Name

Vex 6

### Game Description

Vex 6 is the sixth game in the Vex series. It features tough platforming, interesting mechanics, and many stages for you to play through.

### Game URL

https://zgrapes.1447621498.repl.co/games/vex6/

### Game Type

Online

### Game Tags/Genres

Platformer

**Comment by cohenerickson** [comment]
Added in [v4.1.0](https://github.com/Radon-Games/Radon-Games/releases/tag/v4.1.0)
