### ISSUE TITLE
discord no longer works

### ISSUE THREAD

**Issue by 9nbnibnb** [Radon-Games/Radon-Games#11]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cohenerickson** [comment]
Please supply more information.

**Comment by 9nbnibnb** [comment]
> Please supply more information.

The Google and discord and geforce now area have stopped working for me if you still need info i can try to provide an ss for you

**Comment by cohenerickson** [comment]
Fixed in 2.2.0
