### ISSUE TITLE
Add a Flash Opener

### ISSUE THREAD

**Issue by The-Rock-21** [Radon-Games/Radon-Games#117]
Add flash opener.
(Tried to use ChatGPT to convince this guy. It didn't work. So kids remember, don't use ChatGPT to do your work for you)

**Comment by The-Entity-Aka-Backroom-69** [comment]
Can you add a flash opener tho?

**Comment by Notplayingallday383** [comment]
just use ruffle lol or if its blocked just use the proxy to access [ruffle](https://ruffle.rs/demo)

**Comment by The-Rock-21** [comment]
Using a proxy to access ruffle makes ruffle run slower.

**Comment by cohenerickson** [comment]
duplicate of #91
