### ISSUE TITLE
[BUG]: I cannot access a website.

### ISSUE THREAD

**Issue by GustyCube** [Radon-Games/Radon-Games#122]
My website 'gustycube.xyz' is not accessible due to an internal sever error.

**Comment by cohenerickson** [comment]
Where is the relevance to Radon? If it is your website it is your responsibility to keep online. I'm not sure what you expect me to do about this.

**Comment by GustyCube** [comment]
SOrry using the proxy tab.

**Comment by cohenerickson** [comment]
Likely your school blocking the proxy server, there isn't much one can do about this.
