### ISSUE TITLE
Issue when deploying (PNPM version)

### ISSUE THREAD

**Issue by noahdossan** [Radon-Games/Radon-Games#130]
I use koyweb.com. When I try to deploy it returns an error:
- Debug info
  - Corepack Requirement Error
! A pnpm lockfile (`pnpm-lock.yaml`) was detected, but the
! version of `pnpm` to install could not be determined.
!
! `pnpm` may be installed via the `heroku/nodejs-corepack`
! buildpack. It requires the desired `pnpm` version to be set
! via the `packageManager` key in `package.json`.
!
! To set `packageManager` in `package.json` to the latest
! `pnpm`, run:
!
! `corepack enable`
! `corepack use pnpm@*`
!
! Then commit the result, and try again.
I did what it told me and got this:
Installing pnpm@9.0.0-alpha.7 in the project...

 ERR_PNPM_BAD_PM_VERSION  This project is configured to use v9.0.0-alpha.7+sha256.04fbfe5b989d5f70a387680f09c66fe35ef5bfd9186d7bd867c3f3a335785bd2 of pnpm. Your current pnpm is v9.0.0

I am new to this stuff so what do I do?

**Comment by IncognitoTGT** [comment]
add 
`"packageManager": "pnpm@latest"` in your package.json

**Comment by cohenerickson** [comment]
Strange that they don't default to the latest version, applying the fix above should hopefully fix the issue.
