### ISSUE TITLE
Roblox detects vpn

### ISSUE THREAD

**Issue by 3kh0** [Radon-Games/Radon-Games#25]
![image](https://user-images.githubusercontent.com/58097612/193657207-17b4dd61-40de-4bce-89aa-f13da52b9bcb.png)

https://radon.games/game/roblox

**Comment by cohenerickson** [comment]
resolved in [83bc1c8](https://github.com/Radon-Games/Radon-Games/commit/83bc1c82db66c407fe1f10942369292fea826e4e)
