### ISSUE TITLE
Dogeminer 2 not working

### ISSUE THREAD

**Issue by DanielTheBomb162** [Radon-Games/Radon-Games#26]
**Describe the bug**

**To Reproduce**
1. Go to Radon Games
2. Click on Dogeminer
3. Wait for game to load
4. Proxy is being blocked by Cloudfare

**Expected behavior**
I wanted the game to load properly so I could source it to my game site.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser - Chrome
 - Version 22

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cohenerickson** [comment]
Ultraviolet doesn't support dogeminer, it has been removed in [856e95f](https://github.com/Radon-Games/Radon-Games/commit/856e95f797dee2fca8e2f1d2c6793956e8848875)
