### ISSUE TITLE
NOTHING WORKS!

### ISSUE THREAD

**Issue by Darkatdusk** [Radon-Games/Radon-Games#28]
**Describe the bug**
When I go to myessay.live one of radon websites no games work.

**To Reproduce**
1. Go to 'myessay.live'
2. Click on 'Games'
3. Scroll down to 'any game'

**Expected behavior**
Games should work.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows for Education 2018.05.10
 - Browser Chrome
 - Version 106

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cohenerickson** [comment]
Closing in order to keep private links out of immediate public view, please edit this issue and remove the link.
