### ISSUE TITLE
Build process hangs

### ISSUE THREAD

**Issue by Harlan124** [Radon-Games/Radon-Games#30]
When using free services such as Replit, the Build process hangs.

```
solid-start building client...
solid-start rendering index.html...
```

**Comment by TacoError** [comment]
replit, heroku

**Comment by Harlan124** [comment]
how on heroku????

**Comment by Harlan124** [comment]
it gets stuck on     
       solid-start building client...
       solid-start rendering index.html...

**Comment by cohenerickson** [comment]
> it gets stuck on     
> 
>        solid-start building client...
> 
>        solid-start rendering index.html...

this is a known issue, I am working on an update that will fix the build process. In the mean time make sure you are using the latest version of node js as this may be a factor.
