### ISSUE TITLE
Pokemon Heartgold

### ISSUE THREAD

**Issue by AmongUsSussyBaka42069** [Radon-Games/Radon-Games#42]
**Pokemon Heartgold**

**Pokemon Heartgold is a JRPG Pokemon game made on September 12, 2009, using creatures to fight other creatures.**

**https://emulatorgames.online/games/nds/pokemon-heartgold-version**

**Comment by cohenerickson** [comment]
Added in [v4.1.0](https://github.com/Radon-Games/Radon-Games/releases/tag/v4.1.0)
