### ISSUE TITLE
game request

### ISSUE THREAD

**Issue by aidans-sleeping** [Radon-Games/Radon-Games#45]
**xbox cloud gaming**
The name of the game you want to request.

**its like geforce **
A brief description of the game (so we add the right one).

**https://www.xbox.com/en-us/play**
The URL of the game's website or a playable version of the game.

**i like what yall do and if you guys can get back what vpn do you guys use?**
Add any other information about the game here.

**Comment by cohenerickson** [comment]
Use proxy.

**Comment by aidans-sleeping** [comment]
what proxy
