### ISSUE TITLE
Chaos Faction 2 Game Request

### ISSUE THREAD

**Issue by Gabrsand47** [Radon-Games/Radon-Games#48]
Chaos Faction 2
The name of the game you want to request.

**Description**
A brief description of the game (so we add the right one). A old popular flash game.

**URL**
[The URL of the game's website or a playable version of the game.] ( https://archive.org/details/chaos-faction-2-5645 )

**Additional information**
Add any other information about the game here. NADA

**Comment by cohenerickson** [comment]
Moved to Discord https://discord.gg/t3d7wDA9WY
