### ISSUE TITLE
Game Request - ClassiCube

### ISSUE THREAD

**Issue by Mothq** [Radon-Games/Radon-Games#53]
**Name of Game**
ClassiCube

**Description**
sandbox block game inspired by Minecraft Classic

**URL**
(https://www.classicube.net/)

**Additional information**
I've seen versions on other sites where you can sign in and use the default texture pack. However, that isn't the version they have on the official site.

**Comment by cohenerickson** [comment]
Too similar to
https://radon.games/game/minecraft
