### ISSUE TITLE
Proxy not working

### ISSUE THREAD

**Issue by rusdevofficial** [Radon-Games/Radon-Games#61]
The proxy is down, when loading it gives a 404 - Page Not Found no matter what.
[Screen recording 2023-01-17 10.25.04.webm](https://user-images.githubusercontent.com/63070424/212939088-c255b824-5939-4901-8802-57d48b0bf3bb.webm)
Performed on ChromeOS, Lenovo, Version 107.0.5304.110 (Official Build) (64-bit) (Most recent update). The proxy attempts to run at https://radon.games/~/hvtrs8%2F-wuw%2Cgmoelg.aoo%2F.

**Comment by cohenerickson** [comment]
Fixed in [v3.1.1](https://github.com/Radon-Games/Radon-Games/releases/tag/v3.1.1)
