### ISSUE TITLE
for the apps, all the apps when clicked says 404 Not Found

### ISSUE THREAD

**Issue by McDave135** [Radon-Games/Radon-Games#64]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cohenerickson** [comment]
Fixed in [v3.1.1](https://github.com/Radon-Games/Radon-Games/releases/tag/v3.1.1)
