### ISSUE TITLE
sonic games like sonic advance or 2

### ISSUE THREAD

**Issue by McDave135** [Radon-Games/Radon-Games#65]
**Name of Game**
The name of the game you want to request.

**Description**
A brief description of the game (so we add the right one).

**URL**
The URL of the game's website or a playable version of the game.

**Additional information**
Add any other information about the game here.

**Comment by lashaneross** [comment]
sonic advance 3

**Comment by cohenerickson** [comment]
Added in [v4.1.0](https://github.com/Radon-Games/Radon-Games/releases/tag/v4.1.0)
