### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by Harlan124** [Radon-Games/Radon-Games#70]
Now once I deploy it (which it works) but then once I click on the website it says not found (I am using onrender)

**Comment by cohenerickson** [comment]
Can you please provide more information

**Comment by Harlan124** [comment]
this is what it says after i deploy it 
![image](https://user-images.githubusercontent.com/107516488/214387195-726a75db-9efe-4518-9cf6-3187d5159b5b.png)

**Comment by Harlan124** [comment]
when I click on the link

**Comment by cohenerickson** [comment]
What are you using to host Radon?
What version of Node are you running?

I need more information other than "it doesn't work" to diagnose the issue.

**Comment by Harlan124** [comment]
onrender  and the newest

**Comment by GreenyDEV** [comment]
Dude developers are not mind readers..

**Comment by cohenerickson** [comment]
I have no idea what you mean when you say onrender. If you can provide some sort of logs that would get us somewhere here

**Comment by GreenyDEV** [comment]
I think they were saying the platform is render.app and the node version is the latest lts. I recommend just closing issues like these because people shouldn't do this.
