### ISSUE TITLE
everytime that I put my mouse on google in the apps page and I make sure I click it and nothing happens no tab opens no refresh no nothing it just does nothing

### ISSUE THREAD

**Issue by Diegosmart** [Radon-Games/Radon-Games#71]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by cohenerickson** [comment]
Are you still experiencing the issue?

**Comment by cohenerickson** [comment]
Unable to reproduce/ legacy feature.
