### ISSUE TITLE
[Bug]: Radon not working on nebula

### ISSUE THREAD

**Issue by Cattn** [Radon-Games/Radon-Games#78]
### Describe the bug

Nebula-proxy (official partner?) games break while using

### Steps To Reproduce

Seems like it fully breaks all games when using nebula-proxy on radon games (Game page linked)

![image](https://user-images.githubusercontent.com/69491394/216222496-3cee270e-2de6-4b82-be14-25407db15fbc.png)

1. Go to Nebula

2. Click Games button

### Expected behavior

Expected games to load properly

**Comment by cohenerickson** [comment]
This was an issue with Ultraviolet, it should now be patched in the latest version of `@titaniumnetwork-dev/ultraviolet`
