### ISSUE TITLE
[Ultraviolet Bug]: Inability to connect to hCaptcha

### ISSUE THREAD

**Issue by Jisenku** [Radon-Games/Radon-Games#81]
### Describe the bug

Inability to connect to hCaptcha

### Steps To Reproduce

Go to [url]/apps
Click 'Discord'
Sign in
Click 'I am Human'

### Expected behavior

It keeps trying to load something until eventually it just gives up

### Additional context

Using my own fork of the project, via cyclic.app

Chrome OS
Version 109.0.5414.125 (Official Build) (64-bit)

**Comment by Jisenku** [comment]
This is a general issue, with Google having the same issue if it detects that you seem like a bot, with their captcha not even showing

**Comment by Jisenku** [comment]
> [Ultraviolet](https://github.com/titaniumnetwork-dev/Ultraviolet) issue; not Radon.

Thank you, I'll conduct further research to find a solution

**Comment by cohenerickson** [comment]
Closing this as of now, feel free to reopen it if you feel this is still relevant to Radon.
