### ISSUE TITLE
Apps

### ISSUE THREAD

**Issue by 1234abc5678** [Radon-Games/Radon-Games#85]
### Describe the bug

When you try clicking on google or youtube or any of the other apps, they don't work and it shows the code.

### Steps To Reproduce

Go to the apps button at the top, click on apps. Then click on google or youtube or any of the other apps, and it should show you the code, and it wont take you there.

### Expected behavior

I expect that this should be able to be fixed since it seems there might just be a bug

**Comment by cohenerickson** [comment]
Closing this for now, this is a byproduct of the recent downtime and should be resolved in the next day or two.

**Comment by 1234abc5678** [comment]
ok sweet
