### ISSUE TITLE
[Bug]: CDN Blocked on school network

### ISSUE THREAD

**Issue by Baggette** [Radon-Games/Radon-Games#87]
### Describe the bug

CDN blocked.

### Steps To Reproduce

Even when you self host this game proxy using a server thats remote from my school, this site won't function because radon's cdn is blocked. I suggest maybe implementing a way for data to be cached or downloaded locally or maybe even a small uv proxy build into radon so it can proxy the cdn to the remote server so its not blocked.

### Expected behavior

The site should function as normal, games shoult launch and run without any mojor issues.

**Comment by cohenerickson** [comment]
This shouldn't be the case, self hosted instances already proxy games using an expressjs http proxy. I will have to look further into it.

**Comment by Baggette** [comment]
> This shouldn't be the case, self hosted instances already proxy games using an expressjs http proxy. I will have to look further into it.

hmm that is strange, if there’s anything I can provide let me know.

**Comment by cohenerickson** [comment]
I made some changes in 26b60e9 that might fix the issue, the thing I can think of that might be causing this issue is if you are self-hosting through the school network, in that case, there isn't any easy fix for this.

**Comment by Baggette** [comment]
> I made some changes in [26b60e9](https://github.com/Radon-Games/Radon-Games/commit/26b60e97e15988e23e95126742622cbedf183437) that might fix the issue, the thing I can think of that might be causing this issue is if you are self-hosting through the school network, in that case, there isn't any easy fix for this.

I will update it and test it on monday (when I have school) and no its not being hosted on the school network

**Comment by Baggette** [comment]
oops clicked the wrong thing lol

**Comment by Baggette** [comment]
> I made some changes in [26b60e9](https://github.com/Radon-Games/Radon-Games/commit/26b60e97e15988e23e95126742622cbedf183437) that might fix the issue, the thing I can think of that might be causing this issue is if you are self-hosting through the school network, in that case, there isn't any easy fix for this.

Yes whatever you did seems to have resolved the issue

**Comment by cohenerickson** [comment]
Good to hear
