### ISSUE TITLE
Emulator games don't load.

### ISSUE THREAD

**Issue by Chanwieu** [Radon-Games/Radon-Games#88]
### Describe the bug

The bug is for the pokemon fire red it goes all black when i try to load up

### Steps To Reproduce

* Navigate to any emulator game

### Expected behavior

* Game loads normally

**Comment by cohenerickson** [comment]
Fixed in [420a5ff](https://github.com/Radon-Games/Radon-Games/commit/420a5ff2b58a31c127bbb5ea8b55a8766d62265a)
