### ISSUE TITLE
Game Request: Deep Space Airships

### ISSUE THREAD

**Issue by CoffeeDoster** [Radon-Games/Radon-Games#90]
### Game Name

Deep Space Airships

### Game Description

A free multiplayer ship construction and combat game. Build a flying battleship with your friends and conquer the skies!

### Game URL

drednot.io

### Game Type

Unknown

### Game Tags/Genres

Multiplayer, Building, Combat

**Comment by cohenerickson** [comment]
Use proxy.

**Comment by CoffeeDoster** [comment]
> Use proxy.

Damn,  this was months ago, but thanks for the late reply LOL.

**Comment by cohenerickson** [comment]
Ive been procrastinating on these game requests for too long, figured I needed to do something about it
