### ISSUE TITLE
[Bug]: Deploying on glitch

### ISSUE THREAD

**Issue by binary-pumpkin** [Radon-Games/Radon-Games#92]
### Describe the bug

when i deploy on glitch it tells me no such file or directery  

### Steps To Reproduce

![Screenshot 2023-03-21 9 27 00 AM](https://user-images.githubusercontent.com/125479258/226620285-f6ad149a-30c8-4a68-b95b-25e1a0569bd2.png)

### Expected behavior

Actually working

**Comment by cohenerickson** [comment]
Radon doesn't support hosting on glitch.
