### ISSUE TITLE
Learn to Fly 3

### ISSUE THREAD

**Issue by sploon3** [Radon-Games/Radon-Games#93]
### Game Name

Learn to Fly 3

### Game Description

Learn to Fly 3 is basically just Learn to Fly 2 but there are omega items and spaceships.

### Game URL

https://www.experimonkey.com/games/learn-to-fly-3

### Game Type

Unknown

### Game Tags/Genres

ActionScript3, Games, Funny, Penguins

**Comment by cohenerickson** [comment]
Added in [v4.1.0](https://github.com/Radon-Games/Radon-Games/releases/tag/v4.1.0)
