### ISSUE TITLE
[Bug]: Proxy server is down

### ISSUE THREAD

**Issue by glitch128** [Radon-Games/Radon-Games#97]
### Describe the bug

the proxy at https://uv.radon.games/bare1/ is down

### Steps To Reproduce

go to proxy,
enter search query,
get typescript error: failed to fetch

### Expected behavior

for the proxy to work. that's it

### Additional context

![image](https://user-images.githubusercontent.com/78228404/232916589-d5a22541-8d69-49ba-9c37-6544674c3f2e.png)

**Comment by cohenerickson** [comment]
This is not an issue with Radon. Please do not open any further issues on this topic.

**Comment by cohenerickson** [comment]
I thought I made that clear when I closed your issue on Velocity.
